CREATE TABLE Books (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(200) NOT NULL,
    Author NVARCHAR(100) NOT NULL,
    Genre NVARCHAR(50) DEFAULT 'Fiction',
    Status NVARCHAR(20) DEFAULT 'To Read',
    Rating INT NULL,
    Notes NVARCHAR(MAX) DEFAULT '',
    CoverUrl NVARCHAR(500) DEFAULT '',
    AddedAt DATETIME2 DEFAULT GETUTCDATE()
);
